### ISSUE TITLE
Config file help please?

### ISSUE THREAD

**Issue by nkev** [qrtz/livedev#2]
I would like to try livedev, but I am having issues getting it to compile my project.It runs and parses the livedev.json file but when I refresh the web page, I get this error:

``` Go
BUILD ERROR: GetFileAttributesEx controllers.go: The system cannot find the file specified.
```

Here is my livedev.json file contents (I've tried without the GOROOT and GOPATH server params and also a relative path for the **target** parameter without succes:

``` json
{
    "port":9001,
    "server":[
        {
            "GOROOT":"C:/Go",
            "GOPATH":["C:/Users/Nuri/Dropbox (Personal)/go"],
            "host":"localhost",
            "port": 9000,
            "target":"C:/Users/Nuri/Dropbox (Personal)/go/src/github.com/nkev/web/app/main.go",
            "bin":"/src/github.com/nkev/web/app/web.exe",
            "default":true
        }
    ]
}
```

Here is my directory structure:

![image](https://cloud.githubusercontent.com/assets/5410916/5699520/b5198282-9a7e-11e4-9784-411ce214f428.png)

The command I use from the root "web" folder is:

``` Terminal
livedev -c livedev.json
```

When it runs, I get:

```
Livedev 0.1.8
Host: localhost:9000
Proxy:localhost:9001
```

But when I refresh my browser (Chrome on Windows 8.1) I get the error:

``` Go
BUILD ERROR: GetFileAttributesEx controllers.go: The system cannot find the file specified.
```

Can you see what I'm doing wrong?

**Comment by qrtz** [comment]
All file path options must be absolute. You have a relative path as value of the "bin" option. 
Let me if that helped.

**Comment by nkev** [comment]
Same error. How come the path options are relative in your example?

``` JSON
{
    "port":9001,
    "server":[
        {
            "GOROOT":"C:/Go",
            "GOPATH":["C:/Users/Nuri/Dropbox (Personal)/go"],
            "host":"localhost",
            "port": 9000,
            "target":"C:/Users/Nuri/Dropbox (Personal)/go/src/github.com/nkev/web/app/main.go",
            "bin":"C:/Users/Nuri/Dropbox (Personal)/go/src/github.com/nkev/web/app/web.exe",
            "default":true
        }
    ]
}
```

**Comment by qrtz** [comment]
Are you doing any file manipulation in your code? 
It looks like the error is coming from your "controllers.go"

**Comment by nkev** [comment]
No, there is no file maniulation. Just a Postgres database connection and rendering helpers. The website compiles fine using `go build` and also the "fresh" and "gin" packages that do the same thing as livedev. I like your one because of muliple server support (e.g. dev and production). If I could just get it working... :)

**Comment by qrtz** [comment]
I'm on the road with limited/spotty internet connection. I will take a closer look when I get back. 
Thank you for your feedback.

**Comment by qrtz** [comment]
I have just added a fix that should address your problem.
Please let me know how it works for you.
Your contribution is greatly appreciated.
Thanks

**Comment by nkev** [comment]
It works now, thank you. However, I just realised that your app must run as a proxy (requiring a second proxy port) and not simply as a filewatcher that just compiles when files change. The issue with using a proxy port is that I lose all the fmt.Println() messages that I need for debugging (which get printed on the website port).

**Comment by qrtz** [comment]
The solution is to use the log package and write to a file instead. 
The way I use this tool is the following:
Set the proxy port to 80 so I can access my apps without specifying a port number
Add a host file entry for each app I'm working on.
Design my apps to accept a TCP address through the "addr" argument
No need to specify the server port in the configuration file. 
The tool generates a random port and passes it to my app at startup.
e.g. myapp -addr hostname:[random port]
Thank you.
