### ISSUE TITLE
Unclear workflow

### ISSUE THREAD

**Issue by seanlindo** [qrtz/livedev#3]
Hey there,

I'm not entirely sure how to use this utility. I have two servers defined in my config.json file. The hostnames for both exist in my hosts file and are mapped to 127.0.0.1. The ports that both go apps listen on are also mapped correctly. I don't want this utility listening on Port 80, but it uses the hostname header to proxy the requests. How am I supposed to call my services then?

```
{
    "port": 9000,
    "server":[
        {
            "host": "local.service1.com",
            "port": 5000,
            "target": "/Users/foo/go/src/bitbucket.org/service1/server.go",
            "startupTimeout": 5
        },
        {
            "host": "local.service2.com",
            "port": 5001,
            "target": "/Users/foo/go/src/bitbucket.org/service2/server.go",
            "startupTimeout": 5
        }
    ]
}
```

**Comment by seanlindo** [comment]
Figured it out. I think I'll make a pull request to the documentation though

**Comment by qrtz** [comment]
Sorry for the confusion. Your pull request is welcomed. I appreciate your help.
